packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ~5.9.3
  "@biomejs/biome": ~2.4.15
  next: 16.2.6
  react: 19.2.4
  react-dom: 19.2.4
  "@types/node": ~22.19.19
  "@types/react": ~19.2.0
  "@types/react-dom": ~19.2.0
  tailwindcss: ~4.3.0
  "@tailwindcss/postcss": ~4.3.0
  vitest: ~4.1.7
  server-only: 0.0.1
  drizzle-orm: ~0.45.2
  drizzle-kit: ~0.31.10
